// <auto-generated />
namespace HostContestApp.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SampleMigrations10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SampleMigrations10));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251102137_SampleMigrations10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
